name: Prevent Direct Pushes

on:
  push:
    branches: [ "main" ]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not a PR
        run: |
          echo "Direct pushes to main are not allowed."
          exit 1
